export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const GET_CHATS = 'GET_CHATS'
export const NEW_MSG = 'NEW_MSG'
export const NEW_CHAT = 'NEW_CHAT'
export const GET_MSGS = 'GET_MSGS'
export const DEL_MSG = 'DEL_MES'